[package]
name = "cotowali_source"
version = "0.1.0"
edition = "2021"

[dependencies]
nanoid = "0.4.0"
cotowali_utils = { path = "../cotowali_utils" }
cotowali_chars = { path = "../cotowali_chars" }

[dev-dependencies]
cotowali_asserts = { path = "../cotowali_asserts" }
